Teste_02/config/routes.rb
Rails.application.routes.draw do
  resources :order_books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check
  root "order_books#index"
end

Teste_02/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

Teste_02/app/models/order_book.rb
class OrderBook < ApplicationRecord
    
end

Teste_02/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

Teste_02/app/controllers/order_books_controller.rb
class OrderBooksController < ApplicationController
  before_action :set_order_book, only: %i[ show edit update destroy ]

  # GET /order_books or /order_books.json
  def index
    @order_books = OrderBook.all
    @order_book = OrderBook.new
  end

  # GET /order_books/1 or /order_books/1.json
  def show
  end

  # GET /order_books/new
  def new
    @order_book = OrderBook.new
  end

  # GET /order_books/1/edit
  def edit
  end

  # POST /order_books or /order_books.json
  def create
    @order_book = OrderBook.new(order_book_params)

    respond_to do |format|
      if @order_book.save
        format.html { redirect_to "/order_books/", notice: "Livro Solicitado com Sucesso." }
        format.json { render :show, status: :created, location: @order_book }
      else
        format.html { redirect_to "/order_books/", status: :unprocessable_entity }
        format.json { render json: @order_book.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PATCH/PUT /order_books/1 or /order_books/1.json
  def update
    respond_to do |format|
      if @order_book.update(order_book_params)
        format.html { redirect_to order_book_url(@order_book), notice: "Order book was successfully updated." }
        format.json { render :show, status: :ok, location: @order_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_books/1 or /order_books/1.json
  def destroy
    @order_book.destroy

    respond_to do |format|
      format.html { redirect_to "/order_books/", notice: "Solicitação excluida com Sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_book
      @order_book = OrderBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_book_params
      params.require(:order_book).permit(:bond_type, :title, :author, :edition, :issn, :year_publication, :publishing_company)
    end
end

Teste_02/app/helpers/application_helper.rb
module ApplicationHelper
  
end

Teste_02/app/helpers/order_books_helper.rb
module OrderBooksHelper
end

Teste_02/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
    

      <div style="text-align: right;" class="col-md-6">
        <p></p>
        <div id="timer" class="btn btn-block">00:60</div>
      </div>
      
      <%= yield %>
    </main>
  </body>
</html>

Teste_02/app/views/order_books/_form.html.erb
<%= form_with(model: order_book, :html => {onsubmit: "return validacao()"}) do |form| %>

  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
      <strong><%= message %></strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <%end%>

  <div class="form-group">
   <strong> <%= form.label :'Vínculo*' %></strong>
   <%= form.select :bond_type,["Docente", "Dicente", "Tecnico"], {prompt: true}, class:"form-control", id:"bond_type" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :'Título*' %></strong>
    <%= form.text_field :title, class:"form-control", placeholder: "Digite o título do livro", id:"title" %>
  </div>

  <div class="form-group">
   <strong> <%= form.label :'Autor*'%></strong>
     <%= form.text_field :author, class: "form-control", placeholder: "Digite o autor do livro", id:"author" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :'Edição*' %></strong>
    <%= form.number_field :edition, class:"form-control", placeholder: "Digite a edição do livro", min: 1, id:"edition" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :'issn*' %></strong>
    <%= form.number_field :issn, class:"form-control", placeholder: "Digite o ISSN do livro", min: 1, id:"issn" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :'Ano*' %></strong>
     <%= form.date_select :year_publication, { start_year: 1900, end_year: 2019 }, { class: "datepicker", id:"year" } %>
  </div>

  <div class="form-group">
    <strong><%= form.label :'Editora*' %></strong>
     <%= form.text_field :publishing_company, class: "form-control", id:"publishing_company", placeholder: 'Digite a editora do livro' %>
  </div>

  <div>
    <%= form.submit 'Solicitar Livro', class: 'btn btn-primary', id:"button" %>
  </div>
<% end %>

Teste_02/app/views/order_books/_order_book.html.erb
<h2> Tabela de Solicitação</h2>
<hr />
<table class="table table-striped">
  <thead >
    <tr>
      <th class="col">Vínculo</th>
      <th class="col">Título</th>
      <th class="col">Autor</th>
      <th class="col">Edição</th>
      <th class="col">ISSN</th>
      <th class="col">Ano da Publicação</th>
      <th class="col">Editora</th>
      
    </tr>
  </thead>

  <tbody>
    <% @order_books.each do |order_book| %>
      <tr>
        <td> <strong><%= order_book.bond_type %></strong></td>
        <td><%= order_book.title %></td>
        <td><%= order_book.author %></td>
        <td><%= order_book.edition %></td>
        <td><%= order_book.issn %></td>
        <td><%= order_book.year_publication %></td>
        <td><%= order_book.publishing_company %></td>
        <td><%= button_to 'Deletar', order_book, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Teste_02/app/views/order_books/edit.html.erb
<h1>Editing order book</h1>

<%= render "form", order_book: @order_book %>

<br>

<div>
  <%= link_to "Show this order book", @order_book %> |
  <%= link_to "Back to order books", order_books_path %>
</div>

Teste_02/app/views/order_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Solicitações de Livros</h1>

<div id="new_book">
    <%= render "form", order_book: OrderBook.new %>
</div>

<br/>

<div id="order_books">
 
    <%= render @order_book %>
   
 
</div>

Teste_02/app/views/order_books/new.html.erb
<h1>New order book</h1>

<%= render "form", order_book: @order_book %>

<br>

<div>
  <%= link_to "Back to order books", order_books_path %>
</div>

Teste_02/app/views/order_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_book %>

<div>
  <%= link_to "Edit this order book", edit_order_book_path(@order_book) %> |
  <%= link_to "Back to order books", order_books_path %>

  <%= button_to "Destroy this order book", @order_book, method: :delete %>
  
</div>